### ISSUE TITLE
Complete Tezos part of specification

### ISSUE THREAD

**Issue by indomitableSwan** [boltlabs-inc/zkchannels-spec#66]
Outstanding issues: 
(Those that are not linked currently can be pushed to Milestone 4).
- [x] Specify fee handling
- [ ] Improve clarity and precision; see issue #55.
- [x] Remove indeterminism from tezos contract and propagate as issues in appropriate repo; #34
- [ ] Specify requirements for notification service, including reorg handling.
- [ ] Add Tezos-client requirements; see issue #72
